### ISSUE TITLE
Rewrite in C

### ISSUE THREAD

**Issue by TheRealGlumfish** [vkb24312/platformer#1]
My friend please don't do it. Just use the C. Enough suffering has been had. It's time to call it quits.

**Comment by VinceUB** [comment]
What about this makes you think I'm aiming to be reasonable

**Comment by TheRealGlumfish** [comment]
> What about this makes you think I'm aiming to be reasonable

Please my friend. Please don't do this. There is no turning back if you decide to go forward.
